### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by axelstjerngren** [olliegardner/FindMyConcert#74]
Yes. As per the assessed coursework instruction sheet (attached), tests are required.

Four marks are allocated for unit tests. What tests you decide to use is up to your team’s judgement.
Typically, I’d advise that you include tests for login and logout functionality — perhaps with registration functionality, too.

In addition, I would expect at least one sensible test for each of the key additional features of your app.
Last year, one team submitted a test module with over 500 lines of code! However, some teams didn’t bother at all with tests, and lost 4 easy marks. Somewhere in between those extremes would be ideal.

**Comment by axelstjerngren** [comment]
Just remembered, the venue app should also probably have some unit tests

**Comment by olliegardner** [comment]
Finished unit tests
