### ISSUE TITLE
Edit user forms on profile page aren't saving fields

### ISSUE THREAD

**Issue by olliegardner** [olliegardner/FindMyConcert#92]

**Comment by olliegardner** [comment]
seems to save images but not others?

**Comment by olliegardner** [comment]
Doesn't save attributes defined in GigGoer or Venue (for instance venue_name) class but saves standard django User attributes (email, image)

**Comment by olliegardner** [comment]
Doesn't save password either

**Comment by axelstjerngren** [comment]
Fixed this as well
